package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Authentification generated by hbm2java
 */
public class Authentification  implements java.io.Serializable {


     private Integer idAuth;
     private String login;
     private String pwd;
     private int idUtilisateur;

    public Authentification() {
    }

    public Authentification(String login, String pwd, int idUtilisateur) {
       this.login = login;
       this.pwd = pwd;
       this.idUtilisateur = idUtilisateur;
    }
   
    public Integer getIdAuth() {
        return this.idAuth;
    }
    
    public void setIdAuth(Integer idAuth) {
        this.idAuth = idAuth;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }




}


