package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Classe generated by hbm2java
 */
public class Classe  implements java.io.Serializable {


     private Integer idClasse;
     private String libelle;

    public Classe() {
    }

    public Classe(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdClasse() {
        return this.idClasse;
    }
    
    public void setIdClasse(Integer idClasse) {
        this.idClasse = idClasse;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


