package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Elimine generated by hbm2java
 */
public class Elimine  implements java.io.Serializable {


     private Integer idElimine;
     private int idEtudiant;
     private int idMatiere;
     private int ndAbscr;
     private int ndAbstp;
     private int ndAbstd;
     private int idSemester;

    public Elimine() {
    }

    public Elimine(int idEtudiant, int idMatiere, int ndAbscr, int ndAbstp, int ndAbstd, int idSemester) {
       this.idEtudiant = idEtudiant;
       this.idMatiere = idMatiere;
       this.ndAbscr = ndAbscr;
       this.ndAbstp = ndAbstp;
       this.ndAbstd = ndAbstd;
       this.idSemester = idSemester;
    }
   
    public Integer getIdElimine() {
        return this.idElimine;
    }
    
    public void setIdElimine(Integer idElimine) {
        this.idElimine = idElimine;
    }
    public int getIdEtudiant() {
        return this.idEtudiant;
    }
    
    public void setIdEtudiant(int idEtudiant) {
        this.idEtudiant = idEtudiant;
    }
    public int getIdMatiere() {
        return this.idMatiere;
    }
    
    public void setIdMatiere(int idMatiere) {
        this.idMatiere = idMatiere;
    }
    public int getNdAbscr() {
        return this.ndAbscr;
    }
    
    public void setNdAbscr(int ndAbscr) {
        this.ndAbscr = ndAbscr;
    }
    public int getNdAbstp() {
        return this.ndAbstp;
    }
    
    public void setNdAbstp(int ndAbstp) {
        this.ndAbstp = ndAbstp;
    }
    public int getNdAbstd() {
        return this.ndAbstd;
    }
    
    public void setNdAbstd(int ndAbstd) {
        this.ndAbstd = ndAbstd;
    }
    public int getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(int idSemester) {
        this.idSemester = idSemester;
    }




}


