package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * EnseignantModule generated by hbm2java
 */
public class EnseignantModule  implements java.io.Serializable {


     private Integer idEngmod;
     private int idEnseignant;
     private int idModule;

    public EnseignantModule() {
    }

    public EnseignantModule(int idEnseignant, int idModule) {
       this.idEnseignant = idEnseignant;
       this.idModule = idModule;
    }
   
    public Integer getIdEngmod() {
        return this.idEngmod;
    }
    
    public void setIdEngmod(Integer idEngmod) {
        this.idEngmod = idEngmod;
    }
    public int getIdEnseignant() {
        return this.idEnseignant;
    }
    
    public void setIdEnseignant(int idEnseignant) {
        this.idEnseignant = idEnseignant;
    }
    public int getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(int idModule) {
        this.idModule = idModule;
    }




}


