package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Enseignant generated by hbm2java
 */
public class Enseignant  implements java.io.Serializable {


     private Integer idEnseignant;
     private String matricule;
     private int idUtilisateur;

    public Enseignant() {
    }

    public Enseignant(String matricule, int idUtilisateur) {
       this.matricule = matricule;
       this.idUtilisateur = idUtilisateur;
    }
   
    public Integer getIdEnseignant() {
        return this.idEnseignant;
    }
    
    public void setIdEnseignant(Integer idEnseignant) {
        this.idEnseignant = idEnseignant;
    }
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }




}


