package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private Integer idEtudiant;
     private String carteEtudiant;
     private int idClasse;
    
        private int idUtilisateur;

  
     

    public Etudiant() {
    }

    public Etudiant(String carteEtudiant, int idClasse, int idUtilisateur) {
       this.carteEtudiant = carteEtudiant;
       this.idClasse = idClasse;
      
       this.idUtilisateur = idUtilisateur;
    }
   
    public Integer getIdEtudiant() {
        return this.idEtudiant;
    }
    
    public void setIdEtudiant(Integer idEtudiant) {
        this.idEtudiant = idEtudiant;
    }
    public String getCarteEtudiant() {
        return this.carteEtudiant;
    }
    
    public void setCarteEtudiant(String carteEtudiant) {
        this.carteEtudiant = carteEtudiant;
    }
    public int getIdClasse() {
        return this.idClasse;
    }
    
    public void setIdClasse(int idClasse) {
        this.idClasse = idClasse;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }




}


