package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Integer idModule;
     private String libelle;
     private int idSemester;
     private int idClasse;
     private String amphi;

    public String getAmphi() {
        return amphi;
    }

    public void setAmphi(String amphi) {
        this.amphi = amphi;
    }
    

     

   

    public Module() {
    }

    public Module(String libelle, int idSemester, int idClasse,String amphi) {
       this.libelle = libelle;
       this.idSemester = idSemester;
       this.idClasse = idClasse;
         this.amphi = amphi;
    
       
       
    }
  
    public Integer getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(Integer idModule) {
        this.idModule = idModule;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public int getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(int idSemester) {
        this.idSemester = idSemester;
    }
    public int getIdClasse() {
        return this.idClasse;
    }
    
    public void setIdClasse(int idClasse) {
        this.idClasse = idClasse;
    }




}


