package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * Seancematiere generated by hbm2java
 */
public class Seancematiere  implements java.io.Serializable {


     private Integer idSeanceMatiere;
     private int nbSeanceCr;
     private int nbSeanceTp;
     private int nbSeanceTd;
     private int nbSeance;
     private int idMatiere;

    public Seancematiere() {
    }

    public Seancematiere(int nbSeanceCr, int nbSeanceTp, int nbSeanceTd, int nbSeance, int idMatiere) {
       this.nbSeanceCr = nbSeanceCr;
       this.nbSeanceTp = nbSeanceTp;
       this.nbSeanceTd = nbSeanceTd;
       this.nbSeance = nbSeance;
       this.idMatiere = idMatiere;
    }
   
    public Integer getIdSeanceMatiere() {
        return this.idSeanceMatiere;
    }
    
    public void setIdSeanceMatiere(Integer idSeanceMatiere) {
        this.idSeanceMatiere = idSeanceMatiere;
    }
    public int getNbSeanceCr() {
        return this.nbSeanceCr;
    }
    
    public void setNbSeanceCr(int nbSeanceCr) {
        this.nbSeanceCr = nbSeanceCr;
    }
    public int getNbSeanceTp() {
        return this.nbSeanceTp;
    }
    
    public void setNbSeanceTp(int nbSeanceTp) {
        this.nbSeanceTp = nbSeanceTp;
    }
    public int getNbSeanceTd() {
        return this.nbSeanceTd;
    }
    
    public void setNbSeanceTd(int nbSeanceTd) {
        this.nbSeanceTd = nbSeanceTd;
    }
    public int getNbSeance() {
        return this.nbSeance;
    }
    
    public void setNbSeance(int nbSeance) {
        this.nbSeance = nbSeance;
    }
    public int getIdMatiere() {
        return this.idMatiere;
    }
    
    public void setIdMatiere(int idMatiere) {
        this.idMatiere = idMatiere;
    }




}


