package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private Integer idSeance;
     private int idMatiere;
     private int idClasse;

    public int getIdClasse() {
        return idClasse;
    }

    public void setIdClasse(int idClasse) {
        this.idClasse = idClasse;
    }
     private int idType;
     private Date dateSeance;
     private int idEnseignant;
     private int idSemester;
  

    public Seance() {
    }

    public Seance(int idMatiere,int idClasse ,int idType, Date dateSeance, int idEnseignant, int idSemester) {
       this.idMatiere = idMatiere;
    
       this.idClasse = idClasse;
       this.idType = idType;
       this.dateSeance = dateSeance;
       this.idEnseignant = idEnseignant;
       this.idSemester = idSemester;
    }
   
    public Integer getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(Integer idSeance) {
        this.idSeance = idSeance;
    }
    public int getIdMatiere() {
        return this.idMatiere;
    }
    
    public void setIdMatiere(int idMatiere) {
        this.idMatiere = idMatiere;
    }
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public Date getDateSeance() {
        return this.dateSeance;
    }
    
    public void setDateSeance(Date dateSeance) {
        this.dateSeance = dateSeance;
    }
    public int getIdEnseignant() {
        return this.idEnseignant;
    }
    
    public void setIdEnseignant(int idEnseignant) {
        this.idEnseignant = idEnseignant;
    }
    public int getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(int idSemester) {
        this.idSemester = idSemester;
    }




}


