package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private Integer idSemester;
     private int numsemester;
     private Date datedebutSemester;
     private Date datefinSemester;

    public Semester() {
    }

    public Semester(int numsemester, Date datedebutSemester, Date datefinSemester) {
       this.numsemester = numsemester;
       this.datedebutSemester = datedebutSemester;
       this.datefinSemester = datefinSemester;
    }
   
    public Integer getIdSemester() {
        return this.idSemester;
    }
    
    public void setIdSemester(Integer idSemester) {
        this.idSemester = idSemester;
    }
    public int getNumsemester() {
        return this.numsemester;
    }
    
    public void setNumsemester(int numsemester) {
        this.numsemester = numsemester;
    }
    public Date getDatedebutSemester() {
        return this.datedebutSemester;
    }
    
    public void setDatedebutSemester(Date datedebutSemester) {
        this.datedebutSemester = datedebutSemester;
    }
    public Date getDatefinSemester() {
        return this.datefinSemester;
    }
    
    public void setDatefinSemester(Date datefinSemester) {
        this.datefinSemester = datefinSemester;
    }




}


