package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * TypeUtilisateur generated by hbm2java
 */
public class TypeUtilisateur  implements java.io.Serializable {


     private Integer idType;
     private String libelle;

    public TypeUtilisateur() {
    }

    public TypeUtilisateur(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


