package Model;
// Generated Apr 1, 2016 10:18:00 AM by Hibernate Tools 4.3.1



/**
 * TypeSeance generated by hbm2java
 */
public class TypeSeance  implements java.io.Serializable {


     private Integer idTypes;
     private String libelle;

    public TypeSeance() {
    }

    public TypeSeance(String libelle) {
       this.libelle = libelle;
    }
   
    public Integer getIdTypes() {
        return this.idTypes;
    }
    
    public void setIdTypes(Integer idTypes) {
        this.idTypes = idTypes;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


