package Pojo;
// Generated 12 avr. 2014 14:58:19 by Hibernate Tools 3.6.0



/**
 * Filiere generated by hbm2java
 */
public class Filiere  implements java.io.Serializable {


     private Integer idFiliere;
     private String libelle;
     private String description;

    public Filiere() {
    }

    public Filiere(String libelle, String description) {
       this.libelle = libelle;
       this.description = description;
    }
   
    public Integer getIdFiliere() {
        return this.idFiliere;
    }
    
    public void setIdFiliere(Integer idFiliere) {
        this.idFiliere = idFiliere;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


