package Pojo;
// Generated 12 avr. 2014 14:58:19 by Hibernate Tools 3.6.0



/**
 * Matiers generated by hbm2java
 */
public class Matiers  implements java.io.Serializable {


     private Integer idMatiers;
     private String nom;
     private String description;

    public Matiers() {
    }

    public Matiers(String nom, String description) {
       this.nom = nom;
       this.description = description;
    }
   
    public Integer getIdMatiers() {
        return this.idMatiers;
    }
    
    public void setIdMatiers(Integer idMatiers) {
        this.idMatiers = idMatiers;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


